category: cepcsoft
subdir: Reconstruction/PFA
version: 3.2.1

dep: [GCC, CMake, ROOT, ILCUTIL, Marlin, MarlinUtil]

path:
  lib: '{install}/lib'
  inc: '{install}/include'
  marlin: '{install}/lib/libRanger.so'

source:
  url: http://cepcsoft.ihep.ac.cn/package/cepcsoft/Arbor/{version}/Arbor-{version}.tar.gz
  file: 'Arbor-{version}.tar.gz'
  main: 'Arbor-{version}'

build: [cmake, make, make_install]

install:
  download: http
