category: cepcsoft
subdir: Analysis/SubDetectorStudy
version: 00-01-02

dep: [GCC, CMake, ROOT, ILCUTIL, LCIO, GEAR]

path:
  bin: '{install}/bin'
  lib: '{install}/lib'
  inc: '{install}/include'

source:
  url: https://svnsrv.desy.de/public/bbq/tags/v{version}

build: [cmake, make, make_install]

install:
  download: svn
