category: cepcsoft
subdir: EventDisplay
version: 01-09-01

dep: [GCC, CMake, GLUT, OpenGL, ILCUTIL]

location:
  source: ''
  build: build
  install: ''
path:
  home: '{install}'
  src: '{source}'
  cmake: '{install}'
  bin: '{install}/bin'
  lib: '{install}/lib'
  inc: '{install}/include'

install:
  download:
    handler: svn
    param:
      url: https://svnsrv.desy.de/public/marlinreco/CED/tags/v{version}
  pre_compile:
    handler: patch
    param:
      file: CED-01-09-01.patch
  compile:
    handler: cmake
    param:
      ignore_install_prefix: true
      envcmake:
        BUILD_32BIT_COMPATIBLE: 'OFF'
        INSTALL_DOC: 'OFF'
        CMAKE_BUILD_TYPE: RelWithDebInfo
        CED_SERVER: 'ON'
  clean:
    handler: clean
    param:
      dir: [build, download, log]
