category: cepcsoft
subdir: Reconstruction/Tracking
version: 00-10

dep: [GCC, CMake, ROOT, GSL, ILCUTIL, LCIO, RAIDA, Marlin, MarlinUtil, KalTest, MarlinTrk]

path:
  lib: '{install}/lib'
  inc: '{install}/include'
  marlin: '{install}/lib/libClupatra.so'

source:
  url: https://svnsrv.desy.de/public/marlinreco/Clupatra/tags/v{version}

build: [cmake, make, make_install]

install:
  download: svn
