category: cepcsoft
subdir: Simulation
version: 0-9-6

dep: [GCC, CMake, MySQL, ILCUTIL]

location:
  source: ''
  build: build
  install: ''
path:
  home: '{install}'
  src: '{source}'
  cmake: '{install}'
  lib: '{install}/lib'
  inc: '{install}/include'

install:
  download:
    handler: svn
    param:
      url: https://svnsrv.desy.de/public/calice/CondDBMySQL/tags/CondDBMySQL_ILC-{version}
  compile:
    handler: cmake
    param:
      ignore_install_prefix: true
      envcmake:
        BUILD_32BIT_COMPATIBLE: 'OFF'
        INSTALL_DOC: 'OFF'
        CMAKE_BUILD_TYPE: RelWithDebInfo
  clean:
    handler: clean
    param:
      dir: [build, download, log]
