subdir: Simulation
version: 00-07

dep: [GCC, CMake, XercesC, ROOT, Geant4, CLHEP, LCIO, GEAR]

path:
  bin: '{install}/bin'
  lib: '{install}/lib'
  inc: '{install}/include'

source:
  url: https://svnsrv.desy.de/public/aidasoft/DD4hep/tags/v{version}

cmake:
  var:
    DD4HEP_WITH_GEANT4: '0'
    DD4HEP_USE_XERCESC: '0'
    DD4HEP_USE_PYROOT: '0'

build: [cmake, make, make_install]

install:
  download: svn
