category: cepcsoft
subdir: Service
version: 2.4.2

dep: [GCC]

path:
  cmake: '{install}'
  bin: '{install}/bin'
  lib: '{install}/lib'
  inc: '{install}/include'

source:
  #url: http://www.lpthe.jussieu.fr/~salam/fastjet/repo/fastjet-{version}.tar.gz
  url: http://fastjet.fr/repo/fastjet-{version}.tar.gz
  file: fastjet-{version}.tar.gz
  main: fastjet-{version}

patch: fastjet-2.4.2.patch

configure:
  args: --enable-shared

build: [configure, make, make_install]

install:
  download: http
