subdir: Reconstruction/Tracking
version: 01-07

dep: [GCC, CMake, ROOT, GSL, CLHEP, ILCUTIL, LCIO, GEAR, Marlin, MarlinUtil, MarlinTrk, KiTrack, KiTrackMarlin, RAIDA]

path:
  lib: '{install}/lib'
  inc: '{install}/include'
  marlin: '{install}/lib/libForwardTracking.so'

source:
  url: https://svnsrv.desy.de/public/marlinreco/ForwardTracking/tags/v{version}

build: [cmake, make, make_install]

install:
  download: svn
