category: cepcsoft
subdir: Simulation
version: 03-00-02

dep: [GCC, CMake, XercesC, Geant4, ILCUTIL]

location:
  source: ''
  build: build
  install: ''
path:
  home: '{install}'
  src: '{source}'
  cmake: '{install}'
  lib: '{install}/lib'

install:
  download:
    handler: svn
    param:
      url: svn://svn.freehep.org/lcdet/projects/gdml/tags/v{version}
  compile:
    handler: cmake
    param:
      ignore_install_prefix: true
      envcmake:
        BUILD_32BIT_COMPATIBLE: 'OFF'
        INSTALL_DOC: 'OFF'
        CMAKE_BUILD_TYPE: RelWithDebInfo
  clean:
    handler: clean
    param:
      dir: [build, download, log]
