category: cepcsoft
subdir: Simulation
version: 03-00-02

dep: [GCC, CMake, XercesC, Geant4, ILCUTIL]

path:
  lib: '{install}/lib'

source:
  url: svn://svn.freehep.org/lcdet/projects/gdml/tags/v{version}

build: [cmake, make, make_install]

install:
  download: svn
