category: cepcsoft
subdir: Simulation
version: 3.04.01

dep: [GCC]

path:
  cmake: '{install}'
  lib: '{install}/lib'
  inc: '{install}/include'

source:
  url: http://lcgapp.cern.ch/project/simu/HepPDT/download/HepPDT-{version}.tar.gz
  file: HepPDT-{version}.tar.gz
  main: HepPDT-{version}

build: [configure, make, make_install]

install:
  download: http
