category: cepcsoft
subdir: Simulation
version: 3.04.01

dep: [GCC, CMake]

location:
  source: source
  build: build
  install: install
path:
  home: '{install}'
  src: '{source}'
  cmake: '{install}'
  lib: '{install}/lib'
  inc: '{install}/include'

install:
  download:
    handler: http
    param:
      url: http://lcgapp.cern.ch/project/simu/HepPDT/download/HepPDT-{version}.tar.gz
  extract:
    handler: tar
    param:
      file: HepPDT-{version}.tar.gz
      main: HepPDT-{version}
  compile:
    handler: conf_make
  clean:
    handler: clean
    param:
      dir: [build, download, log]
