subdir: Reconstruction/Tracking
version: 01-05-03

dep: [GCC, CMake, ILCUTIL, ROOT]

path:
  bin: '{install}/bin'
  lib: '{install}/lib'
  inc: '{install}/include'

source:
  url: https://svnsrv.desy.de/public/kaltest/KalTest/tags/v{version}

build: [cmake, make, make_install]

install:
  download: svn
