category: cepcsoft
subdir: Reconstruction/Tracking
version: 01-04

dep: [GCC, CMake, GSL, CLHEP, ROOT, ILCUTIL, Marlin, MarlinUtil, KiTrack, MarlinTrk]

path:
  lib: '{install}/lib'
  inc: '{install}/include'

source:
  url: https://svnsrv.desy.de/public/marlinreco/KiTrackMarlin/tags/v{version}

build: [cmake, make, make_install]

install:
  download: svn
