category: cepcsoft
subdir: Reconstruction/Tracking
version: 01-04

dep: [GCC, CMake, GSL, CLHEP, ROOT, ILCUTIL, Marlin, MarlinUtil, KiTrack, MarlinTrk]

location:
  source: ''
  build: build
  install: ''
path:
  home: '{install}'
  src: '{source}'
  cmake: '{install}'
  lib: '{install}/lib'
  inc: '{install}/include'

install:
  download:
    handler: svn
    param:
      url: https://svnsrv.desy.de/public/marlinreco/KiTrackMarlin/tags/v{version}
  compile:
    handler: cmake
    param:
      ignore_install_prefix: true
      envcmake:
        BUILD_32BIT_COMPATIBLE: 'OFF'
        INSTALL_DOC: 'OFF'
        CMAKE_BUILD_TYPE: RelWithDebInfo
  clean:
    handler: clean
    param:
      dir: [build, download, log]
