category: cepcsoft
subdir: Simulation
version: 01-03

dep: [GCC, CMake, ILCUTIL, LCIO, CondDBMySQL]

path:
  lib: '{install}/lib'
  inc: '{install}/include'

source:
  url: https://svnsrv.desy.de/public/lccd/lccd/tags/v{version}

cmake:
  var:
    LCCD_CONDDBMYSQL: 'ON'

build: [cmake, make, make_install]

install:
  download: svn
