category: cepcsoft
subdir: Simulation
version: 01-03

dep: [GCC, CMake, ILCUTIL, LCIO, CondDBMySQL]

location:
  source: ''
  build: build
  install: ''
path:
  home: '{install}'
  src: '{source}'
  cmake: '{install}'
  lib: '{install}/lib'
  inc: '{install}/include'

install:
  download:
    handler: svn
    param:
      url: https://svnsrv.desy.de/public/lccd/lccd/tags/v{version}
  compile:
    handler: cmake
    param:
      ignore_install_prefix: true
      envcmake:
        BUILD_32BIT_COMPATIBLE: 'OFF'
        INSTALL_DOC: 'OFF'
        CMAKE_BUILD_TYPE: RelWithDebInfo
        LCCD_CONDDBMYSQL: 'ON'
  clean:
    handler: clean
    param:
      dir: [build, download, log]
