category: cepcsoft
subdir: Simulation
version: 03-02-00

dep: [GCC, CMake, XercesC, Geant4, ILCUTIL, GDML]

path:
  lib: '{install}/lib'
  inc: '{install}/include'

env:
  GDML_SCHEMA_DIR: '{install}'

source:
  url: svn://svn.freehep.org/lcdet/projects/lcdd/tags/v{version}

build: [cmake, make, make_install]

install:
  download: svn
