category: cepcsoft
subdir: Reconstruction/PFA/Pandora
version: 00-11

dep: [GCC, CMake, ILCUTIL, Marlin, MarlinUtil, GEAR, PandoraPFANew, LCIO]

location:
  source: ''
  build: build
  install: ''
path:
  home: '{install}'
  src: '{source}'
  cmake: '{install}'
  inc: '{install}/include'
  lib: '{install}/lib'
  marlin: '{install}/lib/libMarlinPandora.so'

install:
  download:
    handler: svn
    param:
      url: https://svnsrv.desy.de/public/PandoraPFANew/MarlinPandora/tags/v{version}
  compile:
    handler: cmake
    param:
      ignore_install_prefix: true
      envcmake:
        BUILD_32BIT_COMPATIBLE: 'OFF'
        INSTALL_DOC: 'OFF'
        CMAKE_BUILD_TYPE: RelWithDebInfo
        PANDORA_MONITORING: 'OFF'
  clean:
    handler: clean
    param:
      dir: [build, download, log]
