category: cepcsoft
subdir: Reconstruction/PFA/Pandora
version: 00-11

dep: [GCC, CMake, ILCUTIL, Marlin, MarlinUtil, GEAR, PandoraPFANew, LCIO]

path:
  inc: '{install}/include'
  lib: '{install}/lib'
  marlin: '{install}/lib/libMarlinPandora.so'

source:
  url: https://svnsrv.desy.de/public/PandoraPFANew/MarlinPandora/tags/v{version}

cmake:
  var:
    PANDORA_MONITORING: 'OFF'

build: [cmake, make, make_install]

install:
  download: svn
