category: cepcsoft
subdir: Reconstruction/Tracking
version: 01-11

dep: [GCC, CMake, GSL, CLHEP, ROOT, ILCUTIL, LCIO, GEAR, Marlin, MarlinUtil, KalTest, KalDet, RAIDA]

path:
  lib: '{install}/lib'
  inc: '{install}/include'

source:
  url: https://svnsrv.desy.de/public/marlinreco/MarlinTrk/tags/v{version}

build: [cmake, make, make_install]

install:
  download: svn
