subdir: Simulation
version: 0.1.1

dep: [GCC, CMake, Geant4, MySQL, HepMC, Boost, ILCUTIL, LCIO, GEAR]

path:
  bin: '{install}/bin'
  lib: '{install}/lib'

source:
  url: http://cepcsoft.ihep.ac.cn/package/cepcsoft/MokkaC/{version}/MokkaC-{version}.tar.gz
  file: MokkaC-{version}.tar.gz
  main: MokkaC-{version}

build: [cmake, make, make_install]

install:
  download: http
