subdir: Analysis
version: 00-13

dep: [GCC, CMake, ROOT, ILCUTIL, Marlin, MarlinUtil, GEAR, LCIO]

path:
  lib: '{install}/lib'
  inc: '{install}/include'
  marlin: '{install}/lib/libOverlay.so'

source:
  url: https://svnsrv.desy.de/public/marlin/Overlay/tags/v{version}

build: [cmake, make, make_install]

install:
  download: svn
