category:
  not_used: {}
  system:
    pre_check: true
  external:
    install: true
    auto_env: true
    version_dir: true
    root: '{software_root}/{platform}/external'
  cepcsoft:
    install: true
    auto_env: true
    version_dir: true
    root: '{software_root}/{platform}/cepcsoft/{version}'
  data:
    install: true
    auto_env: true
    version_dir: true
    root: '{software_root}/data'
  work:
    auto_env: true
    shared: true
    root: 'WORK_ROOT'
  workver:
    auto_env: true
    shared: true
    version_dir: true
    root: 'WORK_VERSION_ROOT'
  standby:
    auto_env: false
    version_dir: true
    root: '{software_root}/{platform}/standby'

category_priority: [work, workver, cepcsoft, external, data, standby]

install:
  steps:
    - download
    - extract
    - patch
    - pre_build
    - configure
    - compile
    - install
    - post_build
    - clean
  atomic_start: pre_build
  atomic_end: post_build

env:
  set_env:
    CEPCSOFT: '{software_root}/{platform}/cepcsoft/{version}'
    CEPCSOFT_EXTERNAL: '{software_root}/{platform}/external'
    CEPCSOFT_DATA: '{software_root}/data'
    CEPCSOFT_VERSION: '{version}'
    CEPCSOFT_PLATFORM: '{platform}'
  append_path:
    BSM_APP_VERSION_PATH: ['cepcenv/{version}']
  unset_env:
    - MARLIN_DLL
  alias:
    hehe: 'xixi lala'
  unalias:
    - hehe
