category: external
version: 2.1.3.1

dep: [GCC, CMake]

path:
  bin: '{install}/bin'
  lib: '{install}/lib'
  pkgconfig: '{install}/lib/pkgconfig'
  inc: '{install}/include'

source:
  url: https://proj-clhep.web.cern.ch/proj-clhep/DISTRIBUTION/tarFiles/clhep-{version}.tgz
  file: clhep-{version}.tgz
  main: '{version}/CLHEP'

build: [cmake, make, make_install]

install:
  download: http
  pre_build: env
