category: external
version: 2.1.3.1

dep: [GCC, CMake]

location:
  source: source
  build: build
  install: install
path:
  home: '{install}'
  src: '{source}'
  cmake: '{install}'
  bin: '{install}/bin'
  lib: '{install}/lib'
  pkgconfig: '{install}/lib/pkgconfig'
  inc: '{install}/include'

install:
  download:
    handler: http
    param:
      url: https://proj-clhep.web.cern.ch/proj-clhep/DISTRIBUTION/tarFiles/clhep-{version}.tgz
  extract:
    handler: tar
    param:
      file: clhep-{version}.tgz
      main: '{version}/CLHEP'
  pre_compile:
    handler: env
  compile:
    handler: cmake
  post_compile:
    handler: lib
  clean:
    handler: clean
    param:
      dir: [build, download, log]
