category: external
version: 2.8.5

dep: GCC

path:
  bin: '{install}/bin'
  man: '{install}/man'

source:
  url: http://www.cmake.org/files/v{version:.3}/cmake-{version}.tar.gz
  file: cmake-{version}.tar.gz
  main: cmake-{version}

build: [configure, make, make_install]

clean: [build, source, download, log]

install:
  download: http
  pre_build: env
