version: '1.14'

dep: [GCC]

path:
  bin: '{install}/bin'
  lib: '{install}/lib'
  inc: '{install}/include'
  man: '{install}/share/man'
  info: '{install}/share/info'
  pkgconfig: '{install}/lib/pkgconfig'
  cmake: '{install}'

source:
  url: http://mirrors.kernel.org/gnu/gsl/gsl-{version}.tar.gz

build: [configure, make, make_install]

install:
  download: http
