version: 3.04.01

dep: [GCC]

path:
  cmake: '{install}'
  lib: '{install}/lib'
  inc: '{install}/include'

source:
#  url: http://lcgapp.cern.ch/project/simu/HepPDT/download/HepPDT-{version}.tar.gz
  url: http://cepcsoft.ihep.ac.cn/package/cepcsoft/HepPDT/{version}/HepPDT-{version}.tar.gz

build: [configure, make, make_install]

install:
  download: http
