category: external
version: 4.7.4

dep: [GCC]

path:
  bin: '{install}/bin'
  lib: '{install}/lib'
  pkgconfig: '{install}/lib/pkgconfig'
  inc: '{install}/include'

source:
  url: http://download.qt.io/archive/qt/{version:.3}/qt-everywhere-opensource-src-{version}.tar.gz
#  url: http://download.qt.io/official_releases/qt/{version:.3}/{version}/qt-everywhere-opensource-src-{version}.tar.gz
  file: qt-everywhere-opensource-src-{version}.tar.gz
  main: qt-everywhere-opensource-src-{version}

configure:
  args:
    - -confirm-license
    - -opensource
    - -prefix-install
    - -fast
    - -make
    - libs
    - -nomake
    - demos
    - -nomake
    - examples
    - -nomake
    - docs
    - -no-separate-debug-info
    - -no-xkb
    - -no-xinerama
    - -no-webkit

build: [configure, make, make_install]

clean: [build, source, download, log]

install:
  download: http
  pre_compile: env
